### ISSUE TITLE
Redundant argument in sprintf

### ISSUE THREAD

**Issue by bokutin** [damil/Data-Domain#3]
<pre>
#!/usr/local/bin/perl

use feature qw(say);
use Data::Domain qw(:all);

say Int->inspect('str');                       # sprintf "invalid number", 'str'
say String(-max_length => 2)->inspect('over'); # sprintf "String: more than %d characters", 2;

__END__
Redundant argument in sprintf at /usr/local/lib/perl5/site_perl/Data/Domain.pm line 376.
Int: invalid number
String: more than 2 characters
</pre>

<pre>
--- lib/Data/Domain.pm.orig     2014-04-05 16:28:32 UTC                    
+++ lib/Data/Domain.pm                                                         
@@ -4,6 +4,7 @@ package Data::Domain; # documentation at end of file
 use 5.010;                                                                    
 use strict;                                                                   
 use warnings;                                                                 
+BEGIN {warnings->unimport(qw/redundant/) if $] >= 5.021002}
 use experimental 'smartmatch';                                                
 use Carp;                                                                     
 use Data::Dumper;   
</pre>

**Comment by damil** [comment]
Hi bokutin,

Thanks for opening this issue. I was really intrigued about the timing, because after many years without touching the Data::Domain module, I noticed this issue a few days ago, and I was just working on it !

I just published v1.07 to CPAN; it should solve the problem
I did not follow exactly your code proposal; I did like in my other module SQL::Abstract::More where this issue also occurred a few years ago : there the fix looks like this :

  no if $] ge '5.022000', warnings => 'redundant';
