### ISSUE TITLE
only one error is returned if ... -exclude => '*' ... is used

### ISSUE THREAD

**Issue by davewood** [damil/Data-Domain#6]
```
use Data::Domain qw/:all/;
  
my $domain = Struct( -fields  => [foo => Int], -exclude => '*');
  
my $data = {
      foo => 'a',
      bar => 'b',
      baz => 'c',
};
  
my $error = $domain->inspect($data);
  
say $error if defined $error;
```

```
perl foo.pl
Struct: contains forbidden field: 'bar'
```

if i delete the "bar" key/value from $data the error will contain the "baz" message.

Shouldn't ALL errors get returned?

**Comment by aldot** [comment]
In my mind all errors should be returned indeed.
Let me try to illustrate what i'd expect:

`
$ cat datadomainissue6.pl ; echo EOF;perl datadomainissue6.pl
#! /usr/bin/env perl
use warnings;
use strict;
use Data::Printer;

use Data::Domain qw/:all/;

my $domain = Struct( -fields  => [foo => Int], -exclude => '*');

my $data = {
      foo => 'a',
      bar => 'b',
      baz => 'c',
};

my $error = $domain->inspect($data);

CORE::say Data::Printer::np $error if defined $error;
EOF
{
    bar   "Struct: contains forbidden field: 'bar'",
    baz   "Struct: contains forbidden field: 'baz'",
    foo   "Int: invalid number"
}

`

I.e.:
`
$ PAGER= git diff 
diff --git a/lib/Data/Domain.pm b/lib/Data/Domain.pm
index 2cb6a6e..8d038d9 100644
--- a/lib/Data/Domain.pm
+++ b/lib/Data/Domain.pm
@@ -1211,21 +1211,23 @@ sub _inspect {
   does($data, 'HASH')
     or return $self->msg(NOT_A_HASH => $data);
 
+  my %msgs;
+  my $has_invalid;
+
   # check if there are any forbidden fields
   if (my $exclude = $self->{-exclude}) {
   FIELD:
     foreach my $field (keys %$data) {
       next FIELD if $self->{-fields}{$field};
 
-      return $self->msg(FORBIDDEN_FIELD => $field)
-        if match::simple::match($field, $exclude)
-        or match::simple::match($exclude, ['*', 'all']);
+      if (match::simple::match($field, $exclude)
+          or match::simple::match($exclude, ['*', 'all'])) {
+        $msgs{$field} = $self->msg(FORBIDDEN_FIELD => $field);
+        $has_invalid = 1;
+      }
     }
   }
 
-  my %msgs;
-  my $has_invalid;
-
   # prepare context for calling lazy subdomains
   $context ||= {root => $data,
                 flat => {},

`

This tests cleanly against
`
commit ad78dcc9c855b7a36b409566a632d27ba8f466d5 (HEAD -> master, origin/master, origin/HEAD)
Author: dami <dami@>
Date:   Mon Apr 24 09:00:55 2023 +0200

    bump to v1.11

`
WDYT?

PS: Please excuse the sloppy pasta

**Comment by damil** [comment]
Hi.
Thanks for raising this issue.
I totally agree that the error message could be more informative, returning the list of all incorrect fields. However I  don't think that it should return a hashref with all wrong fields, because that would conflict with the current API that returns a scalar, and it would also conflict with this statement in the doc :

 > For scalar domains (Num, String, etc.), the error message is just a string. For structured domains (List, Struct), the return value is an arrayref or hashref _of the same structure_

If the return value is a hashref of arbitrary wrong fields, client code would have to anticipate what to do with such a hashref, so handling all possible error cases would be more complex and hardly backwards compatible. 

I would prefer to keep the current API, but pass the full list of wrong fields, i.e something like
```
    my @remaining_fields = grep {!$self->{-fields}{$_}} keys %$data;
    my @wrong_fields     = match::simple::match($exclude, ['*', 'all'])
                           ? @remaining_fields
                           : grep {match::simple::match($_, $exclude)} @remaining_fields;
    return $self->msg(FORBIDDEN_FIELD => join ", ", sort @wrong_fields) if @wrong_fields;`
```
Clients could then choose to just display the error string, or parse the string in order to get back the list of wrong fields.

Would this be OK for your needs ?

**Comment by aldot** [comment]
> > For scalar domains (Num, String, etc.), the error message is just a string. For structured domains (List, Struct), the return value is an arrayref or hashref _of the same structure_

I see. So we could maybe have a separate output (param?) to hold additional error details for structured domains?
my $error_details or $additional_errors or somesuch;
my $error = $domain->inspect($data, $error_details);

and put these additional errors in $error_details iff given?

> 
> If the return value is a hashref of arbitrary wrong fields, client code would have to anticipate what to do with such a hashref, so handling all possible error cases would be more complex and hardly backwards compatible.
> 
> I would prefer to keep the current API, but pass the full list of wrong fields, i.e something like
> 
> ```
>     my @remaining_fields = grep {!$self->{-fields}{$_}} keys %$data;
>     my @wrong_fields     = match::simple::match($exclude, ['*', 'all'])
>                            ? @remaining_fields
>                            : grep {match::simple::match($_, $exclude)} @remaining_fields;
>     return $self->msg(FORBIDDEN_FIELD => join ", ", sort @wrong_fields) if @wrong_fields;`
> ```
> 
> Clients could then choose to just display the error string, or parse the string in order to get back the list of wrong fields.
> 
> Would this be OK for your needs ?

It would work if the type error of `foo "Int: invalid number"` would be emitted in addition to the forbidden fields, yes.
I think it's a pity that the caller has to undo the join in this world though.

think, e.g.:
$data = { foo => 'x', 'com,ma' => 'y', ma => 'a'};
or 'com, ma' and other unhelpful garbage input. Hence maybe an optional param to hold more details that are not bound to the `of the same structure`?

But, whatever works for you.

**Comment by aldot** [comment]
> > > For scalar domains (Num, String, etc.), the error message is just a string. For structured domains (List, Struct), the return value is an arrayref or hashref _of the same structure_

One addition to the statement above.
Maybe one could argue that in the specific case of
`my $domain = Struct( -fields  => [foo => Int], -exclude => '*');`
the Struct is nevertheless free to contain '*' fields (i.e. any) in an error response since it explicitly wants to decline everything but `foo`?
At least that is what i had expected. And i don't think it would break the handling of other (i.e. normal) structured domains at all. But of course it would change the (unhelpful) output of the `exclude *` code as suggested but i'd consider this a feature or fix rather than a new bug. It also would be much simpler to handle throughout, obviously. At least worth considering IMHO.
OTOH i can understand your reluctance to a certain degree.

**Comment by damil** [comment]
I can also understand your point to a certain degree.
Maybe a good compromise would be to keep the current behaviour as default, but offer an option to trigger the new behaviour, either through an IMPORT argument, or directly in the domain constructor, by using a different keyword (for example ``Struct(..., -detailed_exclude => '*')``
I'm not very happy with this example, though ... need to find a better name.

**Comment by damil** [comment]
Just had an new idea : 
``
my $domain = Struct( -fields => [foo => Int], +exclude => '*');
``

The '+' conveys the idea that it's an additional constraint, and with this trick the behaviour can be different from ``-exclude``

**Comment by damil** [comment]
I changed my mind, because I realized that the -keys and -values constraints in Struct() already report their messages within the hashref -- so it's just consistent that -exclude should do the same. 
So in the end I implemented what you initially requested : errors related to -exclude are in the -exclude field; other field errors are intact.
Sorry for the long delay

**Comment by aldot** [comment]
Works fine for me. The issue is resolved as far as i'm concerned.
Many thanks for the fix && cheers
